project 'FirebaseLogin.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseLogin
  
  pod 'Firebase/Core', '~>5.3'
  pod 'Firebase/Auth', '~>5.3'
  pod 'Firebase/Database', '~>5.3'
  pod 'Firebase/Storage', '~> 5.3'

end
